#!/bin/bash

# Test Flow for Stellar Encrypted Token
# This script tests the complete deposit flow

set -e  # Exit on error

export PATH="$HOME/.cargo/bin:$PATH"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Contract and network config
CONTRACT_ID="CBIEPUXAYDOJX5AEADIWJYT76NNYCNIRXUO2SKOY6YNYJG5MAGBPJJWV"
NETWORK="testnet"
USER_KEY="alice"
USER_ADDRESS=$(stellar keys address $USER_KEY)

echo -e "${BLUE}======================================================================${NC}"
echo -e "${BLUE}🧪 TESTING STELLAR ENCRYPTED TOKEN FLOW${NC}"
echo -e "${BLUE}======================================================================${NC}"
echo -e "${YELLOW}Contract ID:${NC} $CONTRACT_ID"
echo -e "${YELLOW}User:${NC} $USER_ADDRESS (using key: $USER_KEY)"
echo -e "${YELLOW}Network:${NC} $NETWORK"
echo ""

# Step 1: Generate encrypted index (simulated - in production this would be generated by client)
echo -e "${GREEN}📋 Step 1: Generate encrypted index${NC}"
echo "In production, the client would:"
echo "  1. Generate a random user index (32 bytes)"
echo "  2. Encrypt it with server's public key"
echo "  3. Send encrypted index to contract"
echo ""
echo "For testing, we'll use a dummy 32-byte value:"
ENCRYPTED_INDEX="0x1111111111111111111111111111111111111111111111111111111111111111"
echo -e "${YELLOW}Encrypted Index:${NC} $ENCRYPTED_INDEX"
echo ""
read -p "Press Enter to continue to Step 2..."
echo ""

# Step 2: Authenticate user (store encrypted index)
echo -e "${GREEN}📋 Step 2: Authenticate user (store encrypted index on-chain)${NC}"
echo "Command:"
echo "stellar contract invoke \\"
echo "  --id $CONTRACT_ID \\"
echo "  --source $USER_KEY \\"
echo "  --network $NETWORK \\"
echo "  -- \\"
echo "  authenticate_user \\"
echo "  --user $USER_ADDRESS \\"
echo "  --encrypted_index $ENCRYPTED_INDEX"
echo ""
read -p "Press Enter to execute..."

stellar contract invoke \
  --id $CONTRACT_ID \
  --source $USER_KEY \
  --network $NETWORK \
  -- \
  authenticate_user \
  --user $USER_ADDRESS \
  --encrypted_index $ENCRYPTED_INDEX

echo -e "${GREEN}✅ User authenticated!${NC}"
echo ""
read -p "Press Enter to continue to Step 3..."
echo ""

# Step 3: Verify user index was stored
echo -e "${GREEN}📋 Step 3: Verify user index was stored${NC}"
echo "Command:"
echo "stellar contract invoke \\"
echo "  --id $CONTRACT_ID \\"
echo "  --source $USER_KEY \\"
echo "  --network $NETWORK \\"
echo "  -- \\"
echo "  get_user_index_by_address \\"
echo "  --user_address $USER_ADDRESS"
echo ""
read -p "Press Enter to execute..."

STORED_INDEX=$(stellar contract invoke \
  --id $CONTRACT_ID \
  --source $USER_KEY \
  --network $NETWORK \
  -- \
  get_user_index_by_address \
  --user_address $USER_ADDRESS)

echo -e "${YELLOW}Stored Index:${NC} $STORED_INDEX"
echo -e "${GREEN}✅ Index verified!${NC}"
echo ""
read -p "Press Enter to continue to Step 4..."
echo ""

# Step 4: Request deposit
DEPOSIT_AMOUNT=1000000
echo -e "${GREEN}📋 Step 4: Request deposit${NC}"
echo "This will:"
echo "  1. Transfer tokens from user to contract (commented out for testing)"
echo "  2. Create a deposit request in contract storage"
echo "  3. Emit 'deposit_requested' event"
echo "  4. Server will detect the event and process it"
echo ""
echo -e "${YELLOW}Amount:${NC} $DEPOSIT_AMOUNT stroops"
echo ""
echo "Command:"
echo "stellar contract invoke \\"
echo "  --id $CONTRACT_ID \\"
echo "  --source $USER_KEY \\"
echo "  --network $NETWORK \\"
echo "  -- \\"
echo "  request_deposit \\"
echo "  --user $USER_ADDRESS \\"
echo "  --amount $DEPOSIT_AMOUNT \\"
echo "  --encrypted_index $ENCRYPTED_INDEX"
echo ""
read -p "Press Enter to execute..."

stellar contract invoke \
  --id $CONTRACT_ID \
  --source $USER_KEY \
  --network $NETWORK \
  -- \
  request_deposit \
  --user $USER_ADDRESS \
  --amount $DEPOSIT_AMOUNT \
  --encrypted_index $ENCRYPTED_INDEX

echo -e "${GREEN}✅ Deposit requested!${NC}"
echo ""
echo -e "${BLUE}======================================================================${NC}"
echo -e "${YELLOW}⏳ Now check your server logs!${NC}"
echo -e "${BLUE}======================================================================${NC}"
echo ""
echo "The server should:"
echo "  1. 🔍 Detect the 'deposit_requested' event"
echo "  2. 📥 Call get_deposit_request() to get full deposit data"
echo "  3. 🔑 Generate/retrieve symmetric key for user"
echo "  4. 🔒 Encrypt the new balance"
echo "  5. 🔐 Encrypt symmetric key for user and server"
echo "  6. 📝 Call store_deposit() to save encrypted data on-chain"
echo "  7. ✅ Emit 'balance_stored' event"
echo ""
read -p "Press Enter when you see the server has processed the deposit..."
echo ""

# Step 5: Verify encrypted balance was stored
echo -e "${GREEN}📋 Step 5: Verify encrypted balance was stored${NC}"
echo ""
echo "The server should have decrypted your encrypted index to get your user_index."
echo "We need to use that same user_index to query the encrypted balance."
echo ""
echo "For this test, we'll use the encrypted index directly as the user_index."
echo "In production, the server decrypts this with its private key."
echo ""
echo "Command:"
echo "stellar contract invoke \\"
echo "  --id $CONTRACT_ID \\"
echo "  --source $USER_KEY \\"
echo "  --network $NETWORK \\"
echo "  -- \\"
echo "  get_encrypted_balance \\"
echo "  --user_index $ENCRYPTED_INDEX"
echo ""
read -p "Press Enter to execute..."

ENCRYPTED_BALANCE=$(stellar contract invoke \
  --id $CONTRACT_ID \
  --source $USER_KEY \
  --network $NETWORK \
  -- \
  get_encrypted_balance \
  --user_index $ENCRYPTED_INDEX)

echo ""
echo -e "${YELLOW}Encrypted Balance Data:${NC}"
echo "$ENCRYPTED_BALANCE" | head -20
echo ""
echo -e "${GREEN}✅ Encrypted balance retrieved!${NC}"
echo ""

# Step 6: Check encrypted supply
echo -e "${GREEN}📋 Step 6: Check total encrypted supply${NC}"
echo "Command:"
echo "stellar contract invoke \\"
echo "  --id $CONTRACT_ID \\"
echo "  --source $USER_KEY \\"
echo "  --network $NETWORK \\"
echo "  -- \\"
echo "  encrypted_supply"
echo ""
read -p "Press Enter to execute..."

SUPPLY=$(stellar contract invoke \
  --id $CONTRACT_ID \
  --source $USER_KEY \
  --network $NETWORK \
  -- \
  encrypted_supply)

echo -e "${YELLOW}Total Encrypted Supply:${NC} $SUPPLY stroops"
echo -e "${GREEN}✅ Supply verified!${NC}"
echo ""

echo -e "${BLUE}======================================================================${NC}"
echo -e "${GREEN}🎉 TEST FLOW COMPLETED SUCCESSFULLY!${NC}"
echo -e "${BLUE}======================================================================${NC}"
echo ""
echo "Summary:"
echo "  ✅ User authenticated with encrypted index"
echo "  ✅ Deposit requested and event emitted"
echo "  ✅ Server detected event and processed deposit"
echo "  ✅ Encrypted balance stored on-chain"
echo "  ✅ Total supply updated"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  - Try another deposit to see balance accumulation"
echo "  - Check server logs to see the encryption process"
echo "  - Verify that only the server can decrypt the balance"
echo ""
